-- MySQL Script generated by MySQL Workbench
-- Sat Jun 10 23:05:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isActive` TINYINT NOT NULL,
  `photo` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persons` (
  `idPersons` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birth_date` VARCHAR(45) NULL,
  `curp` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `rfc` VARCHAR(45) NULL,
  `bussines_name` VARCHAR(45) NULL,
  `fk_use` INT NOT NULL,
  PRIMARY KEY (`idPersons`, `fk_use`),
  CONSTRAINT `fk_Persons_Users`
    FOREIGN KEY (`fk_use`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Persons_Users_idx` ON `mydb`.`Persons` (`fk_use` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Postulations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Postulations` (
  `idPostulations` INT NOT NULL,
  `is_Accept` TINYINT NOT NULL,
  `Persons_idPersons` INT NOT NULL,
  `Persons_fk_use` INT NOT NULL,
  PRIMARY KEY (`idPostulations`, `Persons_idPersons`, `Persons_fk_use`),
  CONSTRAINT `fk_Postulations_Persons1`
    FOREIGN KEY (`Persons_idPersons` , `Persons_fk_use`)
    REFERENCES `mydb`.`Persons` (`idPersons` , `fk_use`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Postulations_Persons1_idx` ON `mydb`.`Postulations` (`Persons_idPersons` ASC, `Persons_fk_use` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `idEvents` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `event_date` DATE NOT NULL,
  `description` TEXT NULL,
  `address` VARCHAR(45) NULL,
  `Persons_idPersons` INT NOT NULL,
  `Persons_fk_use` INT NOT NULL,
  `Postulations_idPostulations` INT NOT NULL,
  `Postulations_Persons_idPersons` INT NOT NULL,
  `Postulations_Persons_fk_use` INT NOT NULL,
  PRIMARY KEY (`idEvents`, `Persons_idPersons`, `Persons_fk_use`, `Postulations_idPostulations`, `Postulations_Persons_idPersons`, `Postulations_Persons_fk_use`),
  CONSTRAINT `fk_Events_Persons1`
    FOREIGN KEY (`Persons_idPersons` , `Persons_fk_use`)
    REFERENCES `mydb`.`Persons` (`idPersons` , `fk_use`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_Postulations1`
    FOREIGN KEY (`Postulations_idPostulations` , `Postulations_Persons_idPersons` , `Postulations_Persons_fk_use`)
    REFERENCES `mydb`.`Postulations` (`idPostulations` , `Persons_idPersons` , `Persons_fk_use`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Events_Persons1_idx` ON `mydb`.`Events` (`Persons_idPersons` ASC, `Persons_fk_use` ASC) VISIBLE;

CREATE INDEX `fk_Events_Postulations1_idx` ON `mydb`.`Events` (`Postulations_idPostulations` ASC, `Postulations_Persons_idPersons` ASC, `Postulations_Persons_fk_use` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Forms` (
  `idForms` INT NOT NULL,
  `name_forms` VARCHAR(45) NOT NULL,
  `Persons_idPersons` INT NOT NULL,
  `Persons_fk_use` INT NOT NULL,
  PRIMARY KEY (`idForms`, `Persons_idPersons`, `Persons_fk_use`),
  CONSTRAINT `fk_Forms_Persons1`
    FOREIGN KEY (`Persons_idPersons` , `Persons_fk_use`)
    REFERENCES `mydb`.`Persons` (`idPersons` , `fk_use`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Forms_Persons1_idx` ON `mydb`.`Forms` (`Persons_idPersons` ASC, `Persons_fk_use` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Questions` (
  `idQuestions` INT NOT NULL,
  `question` VARCHAR(45) NULL,
  `Forms_idForms` INT NOT NULL,
  `Forms_Persons_idPersons` INT NOT NULL,
  `Forms_Persons_fk_use` INT NOT NULL,
  PRIMARY KEY (`idQuestions`, `Forms_idForms`, `Forms_Persons_idPersons`, `Forms_Persons_fk_use`),
  CONSTRAINT `fk_Questions_Forms1`
    FOREIGN KEY (`Forms_idForms` , `Forms_Persons_idPersons` , `Forms_Persons_fk_use`)
    REFERENCES `mydb`.`Forms` (`idForms` , `Persons_idPersons` , `Persons_fk_use`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Questions_Forms1_idx` ON `mydb`.`Questions` (`Forms_idForms` ASC, `Forms_Persons_idPersons` ASC, `Forms_Persons_fk_use` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Persons_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persons_answers` (
  `idPersons_answers` INT NOT NULL,
  PRIMARY KEY (`idPersons_answers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answers` (
  `idAnswers` INT NOT NULL,
  `answer` VARCHAR(45) NULL,
  `isCorrect` VARCHAR(45) NULL,
  `Questions_idQuestions` INT NOT NULL,
  `Questions_Forms_idForms` INT NOT NULL,
  `Questions_Forms_Persons_idPersons` INT NOT NULL,
  `Questions_Forms_Persons_fk_use` INT NOT NULL,
  `Persons_answers_idPersons_answers` INT NOT NULL,
  PRIMARY KEY (`idAnswers`, `Questions_idQuestions`, `Questions_Forms_idForms`, `Questions_Forms_Persons_idPersons`, `Questions_Forms_Persons_fk_use`, `Persons_answers_idPersons_answers`),
  CONSTRAINT `fk_Answers_Questions1`
    FOREIGN KEY (`Questions_idQuestions` , `Questions_Forms_idForms` , `Questions_Forms_Persons_idPersons` , `Questions_Forms_Persons_fk_use`)
    REFERENCES `mydb`.`Questions` (`idQuestions` , `Forms_idForms` , `Forms_Persons_idPersons` , `Forms_Persons_fk_use`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answers_Persons_answers1`
    FOREIGN KEY (`Persons_answers_idPersons_answers`)
    REFERENCES `mydb`.`Persons_answers` (`idPersons_answers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Answers_Questions1_idx` ON `mydb`.`Answers` (`Questions_idQuestions` ASC, `Questions_Forms_idForms` ASC, `Questions_Forms_Persons_idPersons` ASC, `Questions_Forms_Persons_fk_use` ASC) VISIBLE;

CREATE INDEX `fk_Answers_Persons_answers1_idx` ON `mydb`.`Answers` (`Persons_answers_idPersons_answers` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Event_has_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event_has_photos` (
  `idEvent_has_photos` INT NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `Events_idEvents` INT NOT NULL,
  `Events_Persons_idPersons` INT NOT NULL,
  `Events_Persons_fk_use` INT NOT NULL,
  `Events_Postulations_idPostulations` INT NOT NULL,
  `Events_Postulations_Persons_idPersons` INT NOT NULL,
  `Events_Postulations_Persons_fk_use` INT NOT NULL,
  PRIMARY KEY (`idEvent_has_photos`, `Events_idEvents`, `Events_Persons_idPersons`, `Events_Persons_fk_use`, `Events_Postulations_idPostulations`, `Events_Postulations_Persons_idPersons`, `Events_Postulations_Persons_fk_use`),
  CONSTRAINT `fk_Event_has_photos_Events1`
    FOREIGN KEY (`Events_idEvents` , `Events_Persons_idPersons` , `Events_Persons_fk_use` , `Events_Postulations_idPostulations` , `Events_Postulations_Persons_idPersons` , `Events_Postulations_Persons_fk_use`)
    REFERENCES `mydb`.`Events` (`idEvents` , `Persons_idPersons` , `Persons_fk_use` , `Postulations_idPostulations` , `Postulations_Persons_idPersons` , `Postulations_Persons_fk_use`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Event_has_photos_Events1_idx` ON `mydb`.`Event_has_photos` (`Events_idEvents` ASC, `Events_Persons_idPersons` ASC, `Events_Persons_fk_use` ASC, `Events_Postulations_idPostulations` ASC, `Events_Postulations_Persons_idPersons` ASC, `Events_Postulations_Persons_fk_use` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Configurations` (
  `idPerson_colors` INT NOT NULL,
  `url_color` VARCHAR(45) NULL,
  `Person_colorscol` VARCHAR(45) NULL,
  `Persons_idPersons` INT UNSIGNED NOT NULL,
  `Persons_fk_use` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPerson_colors`, `Persons_idPersons`, `Persons_fk_use`),
  CONSTRAINT `fk_Person_colors_Persons1`
    FOREIGN KEY (`Persons_idPersons` , `Persons_fk_use`)
    REFERENCES `mydb`.`Persons` (`idPersons` , `fk_use`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Person_colors_Persons1_idx` ON `mydb`.`Configurations` (`Persons_idPersons` ASC, `Persons_fk_use` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
